#!/bin/bash
if [ "$1" = backup ]; then
  mkdir -p ~/Tresorit/Apps/backups && tar -cZf ~/Tresorit/Apps/backups/ssh.tgz -C ~ .ssh
  exit
fi

if [ "$1" = restore ]; then
  tar xzf ~/Tresorit/Apps/backups/ssh.tgz -C ~/
  exit
fi

if [ "$1" = delete ]; then
  rm ~/Tresorit/Apps/backups/ssh.tgz
  exit
fi

echo "usage:"
echo " ./ssh backup|restore|delete"
exit 0
